name: Lapsol
favicon: null
layout_spectrum: 0.26053
typography_spectrum: 0.87267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0006341356784105301
  lightness: 0.7051752908155322
  saturation: 0.5656996208708733
  rhythmicContrast: 0.03330813767388463
purpose: []
